# Generated by Django 5.0.4 on 2024-07-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max', models.IntegerField()),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('hotel_id', models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Room_invoice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('invoice_id', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'db_table': 'room_invoice',
            },
        ),
        migrations.CreateModel(
            name='Service_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('service_id', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.CASCADE, to='hotel.service')),
            ],
            options={
                'db_table': 'service_detail',
            },
        ),
    ]
