# Generated by Django 5.0.4 on 2024-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_service_detail_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_invoice',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
