# Generated by Django 5.0.4 on 2024-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_room_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
