# Generated by Django 5.0.4 on 2024-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_room_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_invoice',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
