# Generated by Django 5.0.4 on 2024-07-16 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('departure_time', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=10)),
                ('travel_time', models.CharField(max_length=20)),
                ('pick_point', models.CharField(max_length=100)),
                ('des_point', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('seat_count', models.CharField(max_length=50)),
                ('num_seat', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='Bus_invoice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_ticket', models.IntegerField()),
                ('invoice_id', models.CharField(max_length=50)),
                ('bus_id', models.ForeignKey(db_column='bus_id', on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
            options={
                'db_table': 'bus_invoice',
            },
        ),
    ]
