# Generated by Django 5.0.4 on 2024-07-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_invoice',
            name='invoice_id',
            field=models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='payment.invoice'),
        ),
    ]
