# Generated by Django 5.0.4 on 2024-08-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_bus_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
