# Generated by Django 5.0.4 on 2024-08-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_bus_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_invoice',
            name='QR_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
