# Generated by Django 5.0.4 on 2024-07-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('departure_time', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=10)),
                ('travel_time', models.CharField(max_length=20)),
                ('stop_dicrect', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('seat_class', models.CharField(max_length=50)),
                ('num_seat', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Flight_invoice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_ticket', models.IntegerField()),
                ('flight_id', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('invoice_id', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
            options={
                'db_table': 'flight_invoice',
            },
        ),
    ]
