# Generated by Django 5.0.4 on 2024-07-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='stop_dicrect',
            new_name='stop_direct',
        ),
    ]
