# Generated by Django 5.0.4 on 2024-08-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_rename_stop_dicrect_flight_stop_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_invoice',
            name='id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
