# Generated by Django 5.0.4 on 2024-08-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
