# Generated by Django 5.0.4 on 2024-08-07 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
