# Generated by Django 5.0.4 on 2024-07-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nation', models.CharField(default=None, max_length=50)),
                ('expiration', models.DateField(default=None)),
            ],
            options={
                'db_table': 'passport',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
                ('sex', models.CharField(default=None, max_length=10)),
                ('birthday', models.DateField(default=None)),
                ('phone', models.CharField(default=None, max_length=20)),
                ('email', models.CharField(default=None, max_length=50)),
                ('nationality', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(default=None, max_length=50)),
                ('passport_id', models.ForeignKey(db_column='passport_id', on_delete=django.db.models.deletion.CASCADE, to='user.passport')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
