# Generated by Django 5.0.4 on 2024-07-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_birthday_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_id',
            field=models.ForeignKey(blank=True, db_column='passport_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.passport'),
        ),
    ]
