# Generated by Django 5.0.4 on 2024-07-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_passport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
