# Generated by Django 5.0.4 on 2024-07-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_passport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='nation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
