# Generated by Django 5.0.4 on 2024-07-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('luggage', models.CharField(max_length=20)),
                ('num_of_seat', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'taxi',
            },
        ),
        migrations.CreateModel(
            name='Taxi_area',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pick_point', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'taxi_area',
            },
        ),
        migrations.CreateModel(
            name='Taxi_type',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'taxi_type',
            },
        ),
        migrations.CreateModel(
            name='Taxi_area_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_point_id', models.ForeignKey(db_column='pick_point_id', on_delete=django.db.models.deletion.CASCADE, to='transfer.taxi_area')),
                ('taxi_id', models.ForeignKey(db_column='taxi_id', on_delete=django.db.models.deletion.CASCADE, to='transfer.taxi')),
            ],
            options={
                'db_table': 'taxi_area_detail',
            },
        ),
        migrations.CreateModel(
            name='Taxi_invoice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('departure_day', models.DateField()),
                ('time_start', models.CharField(max_length=20)),
                ('arrival_day', models.DateField()),
                ('time_end', models.CharField(max_length=20)),
                ('invoice_id', models.ForeignKey(db_column='invoice_id', on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
                ('taxi_id', models.ForeignKey(db_column='taxi_id', on_delete=django.db.models.deletion.CASCADE, to='transfer.taxi')),
            ],
            options={
                'db_table': 'taxi_invoice',
            },
        ),
    ]
