# Generated by Django 5.0.4 on 2024-08-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_taxi_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi_area',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxi_invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
